<?php

/**
 * Implements hook_permission().
 */
function student_permission() {
  return array(
    'submit student' => array(
      'title' => t('submit student'),
      'description' => t('submit the form'),
    ),
    'access student list' => array(
      'title' => t('access the student list'),
      'description' => t('access the student list'),
    ),
    'access delete' => array(
      'title' => t('access the delete page'),
      'description' => t('access the delete page'),
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function student_block_info() {
  $blocks = array();
  // Generate listing of blocks from this module, for the admin/block page.
  $blocks['student_info'] = array(
    'info' => t('Student information Block'),
    'title' => t('Student information Block to show current  user information'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * Generates the administrator-defined blocks for display.
 */
function student_block_view($delta) {
  $block = array();
  switch ($delta) {
    case "student_info":
      global $user;
      $user_data = user_load($user->uid);
      $fname = field_get_items('user', $user_data, 'field_first_name');
      $first_name = $fname[0]['value'];
      $lname = field_get_items('user', $user_data, 'field_last_name');
      $last_name = $lname[0]['value'];
      $message = "<h2> First name is :" . $first_name . " </h2></br>"
        . "<h2> Last name is :" . $last_name . " </h2></br>";
      $block['content'] = $message;
      break;
  }
  return $block;
}

/**
 * Implements hook_menu().
 */
function student_menu() {
  $items = array();
  $items['student'] = array(
    'title' => 'Student Information Form',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('submit student'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('student_form'),
    'access callback' => TRUE,
    'file' => 'student.admin.inc',
  );
  /* creating student list page */
  $items['formlist'] = array(
    'title' => 'My Form List',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('access form list'),
    'page callback' => 'student_list',
    'access callback' => TRUE,
    'file' => 'student.admin.inc',
  );
  /* CREATING DELETE PAGE */
  $items['formlist/%/delete'] = array(
    'title' => 'My Form List',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('access student_form_delete'),
    'page callback' => 'student_form_delete',
    'page argument' => array(3),
    'access callback' => TRUE,
    'file' => 'student.admin.inc',
  );
  $items['formlist/%/edit'] = array(
    'title' => 'Student Edit List',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'access arguments' => array('access student_form_edit'),
    'page arguments' => array('student_edit_form'),
    'page argument' => array(1),
    'access callback' => TRUE,
    'file' => 'student.admin.inc',
  );
  return $items;
}
